version: '3.5'

x-base: &base
    restart: always
    networks:
        - internal

x-env: &env
    env_file:
        - ${ENV_FILE:-./env}


services:
    openldap:
        <<: *base
        image: osixia/openldap:1.4.0
        container_name: eaxum-ldap
        hostname: eaxum-ldap
        environment:
            - LDAP_ORGANISATION=eaxum
            - LDAP_DOMAIN=eaxum.com
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=admin
            - LDAP_CONFIG_PASSWORD=config_pass
            - LDAP_BASE_DN=dc=eaxum,dc=com
            - LDAP_READONLY_USER=false
            - LDAP_TLS=false
            - LDAP_TLS_VERIFY_CLIENT=never
            - LDAP_RFC2307BIS_SCHEMA=true
        volumes:
            - ldap_data_base:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
    
    phpldapadmin:
        <<: [*base, *env]
        image: osixia/phpldapadmin:0.9.0
        container_name: phpldapadmin
        hostname: phpldapadmin
        ports: 
            - "8001:80"
        depends_on:
            - openldap

    ldap-manager:
        <<: *base
        image: wheelybird/ldap-user-manager:v1.5
        container_name: ldap-manager
        hostname: ldap-manager
        ports: 
            - "8002:80"
        environment: 
            - SERVER_HOSTNAME=eaxum-ldap
            - LDAP_URI=ldap://eaxum-ldap
            - LDAP_BASE_DN=dc=eaxum,dc=com
            - LDAP_ADMINS_GROUP=admins
            - LDAP_ADMIN_BIND_DN=cn=admin,dc=eaxum,dc=com
            - LDAP_ADMIN_BIND_PWD=admin
            - LDAP_IGNORE_CERT_ERRORS=true
            - LDAP_USER_OU=users
            - DEFAULT_USER_GROUP=users
            - NO_HTTPS=TRUE
        depends_on:
            - openldap
        
volumes:
    ldap_data_base:
        name: ${COMPOSE_PROJECT_NAME}-ldap_data_base
    ldap_config:
        name: ${COMPOSE_PROJECT_NAME}-ldap_config  

networks:
    internal:
        name: ${COMPOSE_PROJECT_NAME:?}-internal
