version: '3.5'


x-zou-build: &zou-build
    image: eaxum/zou:$EAXUM_ZOU_VERSION
    build:
        context: ./zou
        args:
            EAXUM_ZOU_VERSION: ${EAXUM_ZOU_VERSION}
            PREVIEW_FOLDER: ${PREVIEW_FOLDER}
            TMP_DIR: ${TMP_DIR}

services:
    kitsu:
        image: eaxum/kitsu:$KITSU_VERSION
        build:
            context: ./kitsu
            args:
                KITSU_VERSION: ${KITSU_VERSION}

    zou-app:
        <<: *zou-build

    zou-event:
        <<: *zou-build
       
    zou-jobs:
        <<: *zou-build

    genesys:
        image: eaxum/genesys:$GENESYS_VERSION
        build:
            context: ./genesys
            args:
                GENESYS_VERSION: ${GENESYS_VERSION}
