version: '3.5'

x-base: &base
    restart: always
    networks:
        - internal
    volumes:
        - svn_data:/opt/svn
        - /home/asuna/eaxum/genesys/genesys/:/usr/local/lib/python3.10/site-packages/genesys

x-env: &env
    env_file:
        - ${ENV_FILE:-./env}

services:
    genesys:
        <<: [*base, *env]
        # user: root
        container_name: ${COMPOSE_PROJECT_NAME}-genesys
        image: eaxum/genesys:$GENESYS_VERSION
        command: "gunicorn --error-logfile - --access-logfile - -w 3 -k gevent -b :5002 genesys.app:app"
    
    genesys-jobs:
        <<: [*base, *env]
        # user: root
        container_name: ${COMPOSE_PROJECT_NAME}-genesys-jobs
        image: eaxum/genesys:$GENESYS_VERSION
        command: "rq worker -c genesys.job_settings"
    
    svn:
        <<: [*base, *env]
        image: eaxum/svn:0.0.8
        container_name: ${COMPOSE_PROJECT_NAME}-svn
        hostname: svn
        volumes:
            - svn_data:/var/svn
        
volumes:
    svn_data:
        name:  ${COMPOSE_PROJECT_NAME}-svn_data
