version: '3.5'

services:
    kitsu:
        image: eaxum/kitsu:${KITSU_VERSION:-latest}
        build:
            context: ./kitsu
            args:
                KITSU_VERSION: ${KITSU_VERSION:-latest}

    zou-app:
        image: eaxum/zou:${ZOU_VERSION:-latest}
        build:
            context: ./zou
            args:
                ZOU_VERSION: ${ZOU_VERSION:-latest}
                PREVIEW_FOLDER: ${PREVIEW_FOLDER:?}
                TMP_DIR: ${TMP_DIR:-/tmp/zou}

    zou-event:
        image: eaxum/zou:${ZOU_VERSION:-latest}
        build:
            context: ./zou
            args:
                ZOU_VERSION: ${ZOU_VERSION:-latest}
                PREVIEW_FOLDER: ${PREVIEW_FOLDER:?}
                TMP_DIR: ${TMP_DIR:-/tmp/zou}
       
    zou-jobs:
        image: eaxum/zou:${ZOU_VERSION:-latest}
        build:
            context: ./zou
            args:
                ZOU_VERSION: ${ZOU_VERSION:-latest}
                PREVIEW_FOLDER: ${PREVIEW_FOLDER:?}
                TMP_DIR: ${TMP_DIR:-/tmp/zou}

    # genesys:
    #     image: eaxum/genesys:$GENESYS_VERSION
    #     build:
    #         context: ./genesys
    #         args:
    #             GENESYS_VERSION: ${GENESYS_VERSION}
